/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-10-27 13:42:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.webpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java_classes.AdminContact;
import edu.cmu.sphinx.api.Configuration;
import edu.cmu.sphinx.api.LiveSpeechRecognizer;
import edu.cmu.sphinx.api.SpeechResult;
import edu.cmu.sphinx.result.WordResult;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Buy Sell Repeat</title>\r\n");
      out.write("<link href=\"bbr.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\"></head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class = wrapper>\r\n");
      out.write("\r\n");
      out.write("<div id = header>\r\n");
      out.write("\r\n");
      out.write("<div id= logo>\r\n");
      out.write("<a href=\"http://localhost:8080/web-SQL/webpages/index.jsp\"><img src= \"Sample_photos/logo/main_logo.JPG\"></a>\r\n");
      out.write("<div id = Quote>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Pacifico\" rel=\"stylesheet\">\r\n");
      out.write("<p>Buy or sell anything at a price that suits you</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id= links>\r\n");
      out.write("<li class=\"active\"><a href='index.jsp'><span>Home</span></a></li>\r\n");
      out.write("<li class=\"active\"><a href='to_buy.jsp'><span>For sale</span></a></li>\r\n");
      out.write("<li class=\"active\"><a href='login.jsp'><span>Login</span></a></li>\r\n");
      out.write("<li class=\"active\"><a href='contact.jsp'><span>Contact</span></a></li>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div id= microphone_op>\r\n");
      out.write("<form method=\"post\" action=\"\" name=\"form2\" id=\"my_sign-up_form\">\r\n");
      out.write("<ol>\r\n");
      out.write("<li>\r\n");
      out.write("  <input class=\"submit\" type=\"image\" src=\"Sample_photos/buttons/microphone.jpg\" name=\"speech_nav\" value=\"speech_nav\" width=\"30\" height=\"30\"alt=\"Speech_navigation\">\r\n");
      out.write("</li>\r\n");
      out.write("</ol>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class= login>\r\n");
      out.write("<div id= heading>\r\n");
      out.write("<h2>Contact Us</h2>\r\n");
      out.write("<p>Please fill out the details in regards to your inquiry</p>\r\n");
      out.write("        <form method=\"post\" action=\"\" name=\"form2\" id=\"my_sign-up_form\">\r\n");
      out.write("          <ol>\r\n");
      out.write("             <li>\r\n");
      out.write("              <select name=\"DepartmentOption1\">\r\n");
      out.write("                <option value=\"select\">Department</option>\r\n");
      out.write("                <option value=\"Sales\">Sales</option>\r\n");
      out.write("                <option value=\"Customer Service\">Customer Service</option>\r\n");
      out.write("                <option value=\"Tech Support\">Tech support</option>\r\n");
      out.write("               </select>\r\n");
      out.write("            </li>\r\n");
      out.write("             <li>\r\n");
      out.write("              <label for=\"message\">Message</label>\r\n");
      out.write("              <input type=\"text\" name=\"message\">\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <input class=\"submit\" type=\"submit\" name=\"send\" value=\"submit\">\r\n");
      out.write("            </li>\r\n");
      out.write("          </ol>   \r\n");
      out.write("          ");

          if(request.getParameter("send")!= null)
          {
        	  String Department = request.getParameter("DepartmentOption1");
        	  String message = request.getParameter("message");
        	  
        	  AdminContact adminC = new AdminContact(Department, message);
        	  int status = AdminContact.add(adminC);
        	  if(status == 1)
        	  {
        		  System.out.println("Message Sent");
        	  }
        	  else
        		  System.out.println("eror");
        	  
          }
          else if(request.getParameter("speech_nav")!=null)
          {
        		System.out.println("speek into the microphone");
        	    Configuration configer = new Configuration();


            	configer.setAcousticModelPath("resource:/edu/cmu/sphinx/models/en-us/en-us");
            	configer.setDictionaryPath("resource:/edu/cmu/sphinx/models/en-us/cmudict-en-us.dict");
            	configer.setLanguageModelPath("resource:/edu/cmu/sphinx/models/en-us/en-us.lm.bin");
           
            	LiveSpeechRecognizer reco = new LiveSpeechRecognizer(configer);
            	reco.startRecognition(true);
            	SpeechResult results = reco.getResult();
            
            	reco.stopRecognition();
            	String result = results.getHypothesis();
                System.out.println("results are "+result);
                
                if(result.contains("index") || result.contains("home")|| result.contains("home page"))
                {
                	response.sendRedirect("index.jsp");
                }
                else if(result.contains("for sale") || result.contains("buying page")|| result.contains("for sale page"))
                {
                	response.sendRedirect("to_buy.jsp");
                }
                else if(result.contains("contact") || result.contains("contact details")|| result.contains("inquiry page"))
                {
                	response.sendRedirect("contact.jsp");
                }
                else if(result.contains("sign up") || result.contains("sign up page")|| result.contains("join site"))
                {
                	response.sendRedirect("sign-up.jsp");
                }
                else if(result.contains("login") || result.contains("logon")|| result.contains("login page") || result.contains("logon page"))
                {
                	response.sendRedirect("login.jsp");
                }
                else
                {
                	out.println("Sorry i did not understand, please click the button to try again");
                }
            	    
          }
          
      out.write("      \r\n");
      out.write("\t\t </form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class = footer>\r\n");
      out.write("<div id= contact>\r\n");
      out.write("<h5> Contact</h5>\r\n");
      out.write("<p>Email: info@buildbuyrepeat.com</p>\r\n");
      out.write("<p>Phone: 1234567891</P>\r\n");
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id= web_links>\r\n");
      out.write("<a href=\"http://www.facebook.com\"><img src=Sample_photos/icons/facebook.jpg width=\"50\" height=\"50\"></a>\r\n");
      out.write("<a href=\"http://www.twitter.com\"><img src=Sample_photos/icons/twitter.jpg width=\"50\" height=\"50\"></a>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
