/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-09-04 12:58:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.webpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java_classes.Post_advert;
import java.util.ArrayList;

public final class to_005fbuy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Buy Sell Repeat</title>\r\n");
      out.write("<link href=\"bbr.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\"></head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class = wrapper>\r\n");
      out.write("\r\n");
      out.write("<div id = header>\r\n");
      out.write("\r\n");
      out.write("<div id= logo>\r\n");
      out.write("<a href=\"http://localhost:8080/web-SQL/webpages/index.jsp\"><img src= \"Sample_photos/logo/main_logo.JPG\"></a>\r\n");
      out.write("<div id = Quote>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Pacifico\" rel=\"stylesheet\">\r\n");
      out.write("<p>Buy or sell anything at a price that suits you</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id= links>\r\n");
      out.write("<li class=\"active\"><a href='index.jsp'><span>Home</span></a></li>\r\n");
      out.write("<li class=\"active\"><a href='to_buy.jsp'><span>For sale</span></a></li>\r\n");
      out.write("<li class=\"active\"><a href='login.jsp'><span>Login</span></a></li>\r\n");
      out.write("<li class=\"active\"><a href='contact.jsp'><span>Contact</span></a></li>\r\n");
      out.write("</div>\r\n");
      out.write("<div id= microphone_op>\r\n");
      out.write("<form action=\"/action_page.php\">\r\n");
      out.write("  <input type=\"image\" src=\"Sample_photos/buttons/microphone.jpg\" width=\"30\" height=\"30\"alt=\"Speech_navigation\">\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class= search>\r\n");
      out.write("<div id= searhBar>\r\n");
      out.write("<p><b>Refine<b></b></p>\r\n");
      out.write("</div>\r\n");
      out.write("<div id= searchBoxes>\r\n");
      out.write(" <form method=\"post\" action=\"\" name=\"form2\" id=\"my_sign-up_form\">\r\n");
      out.write("          <ol>\r\n");
      out.write("            <li>\r\n");
      out.write("              <label for=\"itemName\"></label>\r\n");
      out.write("              <input type=\"text\" name=\"itemName\">\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("             <select name=\"searchOption1\">\r\n");
      out.write("             <option value=\"select\">please select</option>\r\n");
      out.write("             <option value=\"House_Hold\">House Hold</option>\r\n");
      out.write("             <option value=\"Motor\">Motor</option>\r\n");
      out.write("             <option value=\"technology\">technology</option>\r\n");
      out.write("             <option value=\"Animals\">Animals</option>\r\n");
      out.write("             </select>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <select name=\"search_option2\">\r\n");
      out.write("              <option value=\"select\">please select</option>\r\n");
      out.write("              <option value=\"Ulster\">Ulster</option>\r\n");
      out.write("              <option value=\"Munster\">Munster</option>\r\n");
      out.write("              <option value=\"Leinster\">Leinster</option>\r\n");
      out.write("              <option value=\"Connacht\">Connacht</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <input class=\"submit\" type=\"submit\" name=\"Submit\" value=\"Search\">\r\n");
      out.write("            </li>\r\n");
      out.write("          </ol>\r\n");
      out.write("          ");

          if(request.getParameter("Submit")!= null)
          {
        	  String SearchName = request.getParameter("itemName");
        	  String cateSearch = request.getParameter("searchOption1" );
        	  String provenceSearch = request.getParameter("search_option2");
        	  ArrayList array = new ArrayList();
        	  Post_advert search = new Post_advert();
  			  array = search.SearchByWords(SearchName, cateSearch, provenceSearch);
              
  			for(final Object p:array){
				out.println(p.toString());
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href =\"MessageSeller.jsp\">Contact Seller</a><br>\r\n");
      out.write("\t\t\t\t");


			}
  			
          }
          
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class = footer>\r\n");
      out.write("<div id= contact>\r\n");
      out.write("<h5> Contact</h5>\r\n");
      out.write("<p>Email: info@buildbuyrepeat.com</p>\r\n");
      out.write("<p>Phone: 1234567891</P>\r\n");
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id= web_links>\r\n");
      out.write("<a href=\"http://www.facebook.com\"><img src=Sample_photos/icons/facebook.jpg width=\"50\" height=\"50\"></a>\r\n");
      out.write("<a href=\"http://www.twitter.com\"><img src=Sample_photos/icons/twitter.jpg width=\"50\" height=\"50\"></a>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
